### ISSUE TITLE
The `categorical_dims` actually does not work

### ISSUE THREAD

**Issue by xunzhang** [xingchenwan/Casmopolitan#1]
In current implementation, categorical dimensions must be in the beginning of the vector like `[cat, cat, cat, cont, cont]` but this can not support `[cont, cat, cont, cat]` with `f.categorical_dims`. Could you please fix that? Correct me if I am wrong. Thanks.

**Comment by xingchenwan** [comment]
Hi there,
Thank you for your interest. You are right that currently the codebase expects the format with [cat_dims, cont_dims] and if you shuffle the order it won't work. However, it should be relatively easy to prepare your data into such a format.

I agree that this should be probably be made more explicit in the codebase to remind users to pre-process their data into a compatible format.
