### ISSUE TITLE
How to replicate results for vision data (CIFAR-10)?

### ISSUE THREAD

**Issue by vietvo89** [xingchenwan/Casmopolitan#4]
Hi

Your published study is very interesting to me. It's really cool to use your method for vision domain and blackbox model (deep learning model). You have one section for CIFAR-10 dataset and black-box function is DNN. I'm excited to see how it work efficiently and outperforms SparseRS. Can you give me some instructions or sample code to replicate this result? It could benefit my study and make it more progress. 

Thanks

**Comment by xingchenwan** [comment]
Hi there,

Thanks for your interest. I will upload the code and instruction for the black-box attack task as you requested soon, but please bear with me that this might take a while I clean up the code -- it was written quite a while ago!

Best,
Xingchen

**Comment by vietvo89** [comment]
@xingchenwan, thanks. Hopefully, you can share your implementation soon. I'm waiting for your updated repo to replicate your results and to compare with my method that should be in my paper.

**Comment by xingchenwan** [comment]
@vietvo89 Hi there, the code to run adversarial attack has been uploaded. I'm closing the issue now but feel free re-opening it if you have further questions.

**Comment by vietvo89** [comment]
@xingchenwan Thanks a lot. 

One more thing is that I cannot find `optim.observe(x_next, y_next)` in `MixedOptimizer`. I am not sure where `observe()` method can be found. Is there anything missing in `MixedOptimizer`?

**Comment by xingchenwan** [comment]
Hi,

Do you encounter a bug in trying to run the code? I think MixedOptimizer is class-inherited from Optimizer, which has an observe() method.

Best,
Xingchen

**Comment by vietvo89** [comment]
Thank @xingchenwan , you're right. I didn't encounter any bug. But when changing your code to run with torch model, the results weren't right. I think there are some bugs when loading and transforming input images used by torch and your methods. The other way may be an instance (image)  yielded by your methods is not the right input format of torch models.
