### ISSUE TITLE
The version of tensorflow not match, what's your tensorflow version

### ISSUE THREAD

**Issue by ZhihaoLiu-git** [xingchenwan/Casmopolitan#5]
Casmopolitan-main/mixed_test_func/AdvAttack/tf_models/setup_cifar.py", line 16, in <module>
ModuleNotFoundError: No module named 'tensorflow.contrib'

from tensorflow.contrib.keras.api.keras.models import Sequential
from tensorflow.contrib.keras.api.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.contrib.keras.api.keras.layers import Conv2D, MaxPooling2D
from tensorflow.contrib.keras.api.keras.models import load_model

**Comment by xingchenwan** [comment]
The adversarial code was adapted from BayesOpt attack (https://github.com/rubinxin/BayesOpt_Attack/blob/master/requirements), so 1.6.0 tensorflow should work (it won't work with TF 2.0)

Otherwise I don't think you need tensorflow for the other experiments.
