### ISSUE TITLE
Compatibility with Python 3.10

### ISSUE THREAD

**Issue by TianningGao** [xingchenwan/Casmopolitan#6]
I use Python 3.10 on Ubuntu 22.04. This repository has some compatibility issues with my python version and currently installed packages.
I'm writing this just in case others may have same problems as I have. 

In "bo/localbo_utils.py", change line 14 to:
`from typing import Callable`

Files under "mixed_test_func/AdvAttack" requires Tensorflow 1.XX, which is not available from pip3 (python 3.10). Delete this file if you don't need to test the adversarial attack problem. I also deleted "xgboost_hp.py" because I don't need it either. I'm not sure if it's compatible with xgboost 1.7.6, which is latest version from pip3.

Then, run "python3 main.py -p func2C --max_iters 20" to test the code. It finished without any problem on my system.

**Comment by xingchenwan** [comment]
Thanks for note!
